/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/westornd/Documents/UCL/Q7/ELME2002/CVRA/C/motor/feedback/20030.MotorPosition.uavcan
 */

#ifndef MOTOR_FEEDBACK_MOTORPOSITION_HPP_INCLUDED
#define MOTOR_FEEDBACK_MOTORPOSITION_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Motor Position & Velocity
#

float32 position      # [rad]
float16 velocity      # [rad/s]
******************************************************************************/

/********************* DSDL signature source definition ***********************
motor.feedback.MotorPosition
saturated float32 position
saturated float16 velocity
******************************************************************************/

#undef position
#undef velocity

namespace motor
{
namespace feedback
{

template <int _tmpl>
struct UAVCAN_EXPORT MotorPosition_
{
    typedef const MotorPosition_<_tmpl>& ParameterType;
    typedef MotorPosition_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > position;
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > velocity;
    };

    enum
    {
        MinBitLen
            = FieldTypes::position::MinBitLen
            + FieldTypes::velocity::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::position::MaxBitLen
            + FieldTypes::velocity::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::position >::Type position;
    typename ::uavcan::StorageType< typename FieldTypes::velocity >::Type velocity;

    MotorPosition_()
        : position()
        , velocity()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<48 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20030 };

    static const char* getDataTypeFullName()
    {
        return "motor.feedback.MotorPosition";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool MotorPosition_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        position == rhs.position &&
        velocity == rhs.velocity;
}

template <int _tmpl>
bool MotorPosition_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(position, rhs.position) &&
        ::uavcan::areClose(velocity, rhs.velocity);
}

template <int _tmpl>
int MotorPosition_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::position::encode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::encode(self.velocity, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int MotorPosition_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::position::decode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::decode(self.velocity, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature MotorPosition_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x720E4E5E609C274EULL);

    FieldTypes::position::extendDataTypeSignature(signature);
    FieldTypes::velocity::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef MotorPosition_<0> MotorPosition;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::motor::feedback::MotorPosition > _uavcan_gdtr_registrator_MotorPosition;

}

} // Namespace feedback
} // Namespace motor

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::motor::feedback::MotorPosition >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::motor::feedback::MotorPosition::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::motor::feedback::MotorPosition >::stream(Stream& s, ::motor::feedback::MotorPosition::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "position: ";
    YamlStreamer< ::motor::feedback::MotorPosition::FieldTypes::position >::stream(s, obj.position, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "velocity: ";
    YamlStreamer< ::motor::feedback::MotorPosition::FieldTypes::velocity >::stream(s, obj.velocity, level + 1);
}

}

namespace motor
{
namespace feedback
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::motor::feedback::MotorPosition::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::motor::feedback::MotorPosition >::stream(s, obj, 0);
    return s;
}

} // Namespace feedback
} // Namespace motor

#endif // MOTOR_FEEDBACK_MOTORPOSITION_HPP_INCLUDED