/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/westornd/Documents/UCL/Q7/ELME2002/CVRA/C/motor/feedback/20031.MotorTorque.uavcan
 */

#ifndef MOTOR_FEEDBACK_MOTORTORQUE_HPP_INCLUDED
#define MOTOR_FEEDBACK_MOTORTORQUE_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Torque Feedback
#

float16 torque      # [Nm]
float16 position    # [rad]
******************************************************************************/

/********************* DSDL signature source definition ***********************
motor.feedback.MotorTorque
saturated float16 torque
saturated float16 position
******************************************************************************/

#undef torque
#undef position

namespace motor
{
namespace feedback
{

template <int _tmpl>
struct UAVCAN_EXPORT MotorTorque_
{
    typedef const MotorTorque_<_tmpl>& ParameterType;
    typedef MotorTorque_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > torque;
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > position;
    };

    enum
    {
        MinBitLen
            = FieldTypes::torque::MinBitLen
            + FieldTypes::position::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::torque::MaxBitLen
            + FieldTypes::position::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::torque >::Type torque;
    typename ::uavcan::StorageType< typename FieldTypes::position >::Type position;

    MotorTorque_()
        : torque()
        , position()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<32 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20031 };

    static const char* getDataTypeFullName()
    {
        return "motor.feedback.MotorTorque";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool MotorTorque_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        torque == rhs.torque &&
        position == rhs.position;
}

template <int _tmpl>
bool MotorTorque_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(torque, rhs.torque) &&
        ::uavcan::areClose(position, rhs.position);
}

template <int _tmpl>
int MotorTorque_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::torque::encode(self.torque, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::encode(self.position, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int MotorTorque_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::torque::decode(self.torque, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::decode(self.position, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature MotorTorque_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xFD7306F4561E42AFULL);

    FieldTypes::torque::extendDataTypeSignature(signature);
    FieldTypes::position::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef MotorTorque_<0> MotorTorque;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::motor::feedback::MotorTorque > _uavcan_gdtr_registrator_MotorTorque;

}

} // Namespace feedback
} // Namespace motor

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::motor::feedback::MotorTorque >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::motor::feedback::MotorTorque::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::motor::feedback::MotorTorque >::stream(Stream& s, ::motor::feedback::MotorTorque::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "torque: ";
    YamlStreamer< ::motor::feedback::MotorTorque::FieldTypes::torque >::stream(s, obj.torque, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "position: ";
    YamlStreamer< ::motor::feedback::MotorTorque::FieldTypes::position >::stream(s, obj.position, level + 1);
}

}

namespace motor
{
namespace feedback
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::motor::feedback::MotorTorque::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::motor::feedback::MotorTorque >::stream(s, obj, 0);
    return s;
}

} // Namespace feedback
} // Namespace motor

#endif // MOTOR_FEEDBACK_MOTORTORQUE_HPP_INCLUDED