/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/westornd/Documents/UCL/Q7/ELME2002/CVRA/C/motor/feedback/20043.Index.uavcan
 */

#ifndef MOTOR_FEEDBACK_INDEX_HPP_INCLUDED
#define MOTOR_FEEDBACK_INDEX_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Stream the position of the last index passage
#

float16 position
uint32 update_count
******************************************************************************/

/********************* DSDL signature source definition ***********************
motor.feedback.Index
saturated float16 position
saturated uint32 update_count
******************************************************************************/

#undef position
#undef update_count

namespace motor
{
namespace feedback
{

template <int _tmpl>
struct UAVCAN_EXPORT Index_
{
    typedef const Index_<_tmpl>& ParameterType;
    typedef Index_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > position;
        typedef ::uavcan::IntegerSpec< 32, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > update_count;
    };

    enum
    {
        MinBitLen
            = FieldTypes::position::MinBitLen
            + FieldTypes::update_count::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::position::MaxBitLen
            + FieldTypes::update_count::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::position >::Type position;
    typename ::uavcan::StorageType< typename FieldTypes::update_count >::Type update_count;

    Index_()
        : position()
        , update_count()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<48 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20043 };

    static const char* getDataTypeFullName()
    {
        return "motor.feedback.Index";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Index_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        position == rhs.position &&
        update_count == rhs.update_count;
}

template <int _tmpl>
bool Index_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(position, rhs.position) &&
        ::uavcan::areClose(update_count, rhs.update_count);
}

template <int _tmpl>
int Index_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::position::encode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::update_count::encode(self.update_count, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Index_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::position::decode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::update_count::decode(self.update_count, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Index_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x4A4F155962F85400ULL);

    FieldTypes::position::extendDataTypeSignature(signature);
    FieldTypes::update_count::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Index_<0> Index;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::motor::feedback::Index > _uavcan_gdtr_registrator_Index;

}

} // Namespace feedback
} // Namespace motor

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::motor::feedback::Index >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::motor::feedback::Index::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::motor::feedback::Index >::stream(Stream& s, ::motor::feedback::Index::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "position: ";
    YamlStreamer< ::motor::feedback::Index::FieldTypes::position >::stream(s, obj.position, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "update_count: ";
    YamlStreamer< ::motor::feedback::Index::FieldTypes::update_count >::stream(s, obj.update_count, level + 1);
}

}

namespace motor
{
namespace feedback
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::motor::feedback::Index::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::motor::feedback::Index >::stream(s, obj, 0);
    return s;
}

} // Namespace feedback
} // Namespace motor

#endif // MOTOR_FEEDBACK_INDEX_HPP_INCLUDED