/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/westornd/Documents/UCL/Q7/ELME2002/CVRA/C/motor/feedback/20010.MotorEncoderPosition.uavcan
 */

#ifndef MOTOR_FEEDBACK_MOTORENCODERPOSITION_HPP_INCLUDED
#define MOTOR_FEEDBACK_MOTORENCODERPOSITION_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Motor Encoder Position
#

uint16 raw_encoder_position
******************************************************************************/

/********************* DSDL signature source definition ***********************
motor.feedback.MotorEncoderPosition
saturated uint16 raw_encoder_position
******************************************************************************/

#undef raw_encoder_position

namespace motor
{
namespace feedback
{

template <int _tmpl>
struct UAVCAN_EXPORT MotorEncoderPosition_
{
    typedef const MotorEncoderPosition_<_tmpl>& ParameterType;
    typedef MotorEncoderPosition_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 16, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > raw_encoder_position;
    };

    enum
    {
        MinBitLen
            = FieldTypes::raw_encoder_position::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::raw_encoder_position::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::raw_encoder_position >::Type raw_encoder_position;

    MotorEncoderPosition_()
        : raw_encoder_position()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<16 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20010 };

    static const char* getDataTypeFullName()
    {
        return "motor.feedback.MotorEncoderPosition";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool MotorEncoderPosition_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        raw_encoder_position == rhs.raw_encoder_position;
}

template <int _tmpl>
bool MotorEncoderPosition_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(raw_encoder_position, rhs.raw_encoder_position);
}

template <int _tmpl>
int MotorEncoderPosition_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::raw_encoder_position::encode(self.raw_encoder_position, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int MotorEncoderPosition_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::raw_encoder_position::decode(self.raw_encoder_position, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature MotorEncoderPosition_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xFACAE83990663E01ULL);

    FieldTypes::raw_encoder_position::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef MotorEncoderPosition_<0> MotorEncoderPosition;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::motor::feedback::MotorEncoderPosition > _uavcan_gdtr_registrator_MotorEncoderPosition;

}

} // Namespace feedback
} // Namespace motor

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::motor::feedback::MotorEncoderPosition >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::motor::feedback::MotorEncoderPosition::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::motor::feedback::MotorEncoderPosition >::stream(Stream& s, ::motor::feedback::MotorEncoderPosition::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "raw_encoder_position: ";
    YamlStreamer< ::motor::feedback::MotorEncoderPosition::FieldTypes::raw_encoder_position >::stream(s, obj.raw_encoder_position, level + 1);
}

}

namespace motor
{
namespace feedback
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::motor::feedback::MotorEncoderPosition::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::motor::feedback::MotorEncoderPosition >::stream(s, obj, 0);
    return s;
}

} // Namespace feedback
} // Namespace motor

#endif // MOTOR_FEEDBACK_MOTORENCODERPOSITION_HPP_INCLUDED