/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/westornd/Documents/UCL/Q7/ELME2002/CVRA/C/motor/feedback/20041.VelocityPID.uavcan
 */

#ifndef MOTOR_FEEDBACK_VELOCITYPID_HPP_INCLUDED
#define MOTOR_FEEDBACK_VELOCITYPID_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Stream to tune the velocity PID
#

float16 velocity_setpoint
float16 velocity
******************************************************************************/

/********************* DSDL signature source definition ***********************
motor.feedback.VelocityPID
saturated float16 velocity_setpoint
saturated float16 velocity
******************************************************************************/

#undef velocity_setpoint
#undef velocity

namespace motor
{
namespace feedback
{

template <int _tmpl>
struct UAVCAN_EXPORT VelocityPID_
{
    typedef const VelocityPID_<_tmpl>& ParameterType;
    typedef VelocityPID_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > velocity_setpoint;
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > velocity;
    };

    enum
    {
        MinBitLen
            = FieldTypes::velocity_setpoint::MinBitLen
            + FieldTypes::velocity::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::velocity_setpoint::MaxBitLen
            + FieldTypes::velocity::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::velocity_setpoint >::Type velocity_setpoint;
    typename ::uavcan::StorageType< typename FieldTypes::velocity >::Type velocity;

    VelocityPID_()
        : velocity_setpoint()
        , velocity()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<32 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20041 };

    static const char* getDataTypeFullName()
    {
        return "motor.feedback.VelocityPID";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool VelocityPID_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        velocity_setpoint == rhs.velocity_setpoint &&
        velocity == rhs.velocity;
}

template <int _tmpl>
bool VelocityPID_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(velocity_setpoint, rhs.velocity_setpoint) &&
        ::uavcan::areClose(velocity, rhs.velocity);
}

template <int _tmpl>
int VelocityPID_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::velocity_setpoint::encode(self.velocity_setpoint, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::encode(self.velocity, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int VelocityPID_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::velocity_setpoint::decode(self.velocity_setpoint, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::decode(self.velocity, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature VelocityPID_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x2BE4048727C1E983ULL);

    FieldTypes::velocity_setpoint::extendDataTypeSignature(signature);
    FieldTypes::velocity::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef VelocityPID_<0> VelocityPID;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::motor::feedback::VelocityPID > _uavcan_gdtr_registrator_VelocityPID;

}

} // Namespace feedback
} // Namespace motor

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::motor::feedback::VelocityPID >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::motor::feedback::VelocityPID::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::motor::feedback::VelocityPID >::stream(Stream& s, ::motor::feedback::VelocityPID::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "velocity_setpoint: ";
    YamlStreamer< ::motor::feedback::VelocityPID::FieldTypes::velocity_setpoint >::stream(s, obj.velocity_setpoint, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "velocity: ";
    YamlStreamer< ::motor::feedback::VelocityPID::FieldTypes::velocity >::stream(s, obj.velocity, level + 1);
}

}

namespace motor
{
namespace feedback
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::motor::feedback::VelocityPID::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::motor::feedback::VelocityPID >::stream(s, obj, 0);
    return s;
}

} // Namespace feedback
} // Namespace motor

#endif // MOTOR_FEEDBACK_VELOCITYPID_HPP_INCLUDED