#ifndef _ALTERA_ADDRESS_SPAN_EXTENDER_0_H_
#define _ALTERA_ADDRESS_SPAN_EXTENDER_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'address_span_extender_0' and devices
 * connected to the following master:
 *   expanded_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'address_span_extender_0', class 'altera_address_span_extender'.
 * The macros have no prefix.
 */
#define BURSTCOUNT_WIDTH 1
#define BYTEENABLE_WIDTH 4
#define CNTL_ADDRESS_WIDTH 1
#define DATA_WIDTH 32
#define MASTER_ADDRESS_WIDTH 32
#define MAX_BURST_BYTES 4
#define MAX_BURST_WORDS 1
#define SLAVE_ADDRESS_SHIFT 2
#define SLAVE_ADDRESS_WIDTH 25
#define SUB_WINDOW_COUNT 1

/*
 * Macros for device 'hps_0_bridges', class 'hps_bridge_avalon'
 * The macros are prefixed with 'HPS_0_BRIDGES_'.
 * The prefix is the slave descriptor.
 */
#define HPS_0_BRIDGES_COMPONENT_TYPE hps_bridge_avalon
#define HPS_0_BRIDGES_COMPONENT_NAME hps_0_bridges
#define HPS_0_BRIDGES_BASE 0x0
#define HPS_0_BRIDGES_SPAN 0x0
#define HPS_0_BRIDGES_END 0xffffffff


#endif /* _ALTERA_ADDRESS_SPAN_EXTENDER_0_H_ */
