#ifndef _ALTERA_NIOS2_GEN2_0_H_
#define _ALTERA_NIOS2_GEN2_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'nios2_gen2_0' and devices
 * connected to the following masters:
 *   data_master
 *   instruction_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'nios2_gen2_0', class 'altera_nios2_gen2'.
 * The macros have no prefix.
 */
#define BIG_ENDIAN 0
#define BREAK_ADDR 0x21020
#define CPU_ARCH_NIOS2_R1 
#define CPU_FREQ 50000000
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x00000000
#define CPU_IMPLEMENTATION "tiny"
#define DATA_ADDR_WIDTH 28
#define DCACHE_LINE_SIZE 0
#define DCACHE_LINE_SIZE_LOG2 0
#define DCACHE_SIZE 0
#define EXCEPTION_ADDR 0x20
#define FLASH_ACCELERATOR_LINES 0
#define FLASH_ACCELERATOR_LINE_SIZE 0
#define FLUSHDA_SUPPORTED 
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 0
#define HARDWARE_MULX_PRESENT 0
#define HAS_DEBUG_CORE 1
#define HAS_DEBUG_STUB 
#define HAS_ILLEGAL_INSTRUCTION_EXCEPTION 
#define HAS_JMPI_INSTRUCTION 
#define ICACHE_LINE_SIZE 0
#define ICACHE_LINE_SIZE_LOG2 0
#define ICACHE_SIZE 0
#define INST_ADDR_WIDTH 18
#define OCI_VERSION 1
#define RESET_ADDR 0x0

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 100000
#define ONCHIP_MEMORY2_0_END 0x1869f
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 100000
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'jtag_uart_0', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_0_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_0_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_0_COMPONENT_NAME jtag_uart_0
#define JTAG_UART_0_BASE 0x20000
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_END 0x20007
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8

/*
 * Macros for device 'address_span_extender_0_cntl', class 'altera_address_span_extender'
 * The macros are prefixed with 'ADDRESS_SPAN_EXTENDER_0_CNTL_'.
 * The prefix is the slave descriptor.
 */
#define ADDRESS_SPAN_EXTENDER_0_CNTL_COMPONENT_TYPE altera_address_span_extender
#define ADDRESS_SPAN_EXTENDER_0_CNTL_COMPONENT_NAME address_span_extender_0
#define ADDRESS_SPAN_EXTENDER_0_CNTL_BASE 0x20008
#define ADDRESS_SPAN_EXTENDER_0_CNTL_SPAN 8
#define ADDRESS_SPAN_EXTENDER_0_CNTL_END 0x2000f
#define ADDRESS_SPAN_EXTENDER_0_CNTL_BURSTCOUNT_WIDTH 1
#define ADDRESS_SPAN_EXTENDER_0_CNTL_BYTEENABLE_WIDTH 4
#define ADDRESS_SPAN_EXTENDER_0_CNTL_CNTL_ADDRESS_WIDTH 1
#define ADDRESS_SPAN_EXTENDER_0_CNTL_DATA_WIDTH 32
#define ADDRESS_SPAN_EXTENDER_0_CNTL_MASTER_ADDRESS_WIDTH 32
#define ADDRESS_SPAN_EXTENDER_0_CNTL_MAX_BURST_BYTES 4
#define ADDRESS_SPAN_EXTENDER_0_CNTL_MAX_BURST_WORDS 1
#define ADDRESS_SPAN_EXTENDER_0_CNTL_SLAVE_ADDRESS_SHIFT 2
#define ADDRESS_SPAN_EXTENDER_0_CNTL_SLAVE_ADDRESS_WIDTH 25
#define ADDRESS_SPAN_EXTENDER_0_CNTL_SUB_WINDOW_COUNT 1

/*
 * Macros for device 'timer_0', class 'altera_avalon_timer'
 * The macros are prefixed with 'TIMER_0_'.
 * The prefix is the slave descriptor.
 */
#define TIMER_0_COMPONENT_TYPE altera_avalon_timer
#define TIMER_0_COMPONENT_NAME timer_0
#define TIMER_0_BASE 0x20020
#define TIMER_0_SPAN 32
#define TIMER_0_END 0x2003f
#define TIMER_0_IRQ 1
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_LOAD_VALUE 49999
#define TIMER_0_MULT 0.001
#define TIMER_0_PERIOD 1
#define TIMER_0_PERIOD_UNITS ms
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0

/*
 * Macros for device 'dipsw_pio_nios', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_NIOS_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_NIOS_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_NIOS_COMPONENT_NAME dipsw_pio_nios
#define DIPSW_PIO_NIOS_BASE 0x20040
#define DIPSW_PIO_NIOS_SPAN 16
#define DIPSW_PIO_NIOS_END 0x2004f
#define DIPSW_PIO_NIOS_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_NIOS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_NIOS_CAPTURE 1
#define DIPSW_PIO_NIOS_DATA_WIDTH 4
#define DIPSW_PIO_NIOS_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_NIOS_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_NIOS_EDGE_TYPE ANY
#define DIPSW_PIO_NIOS_FREQ 50000000
#define DIPSW_PIO_NIOS_HAS_IN 1
#define DIPSW_PIO_NIOS_HAS_OUT 0
#define DIPSW_PIO_NIOS_HAS_TRI 0
#define DIPSW_PIO_NIOS_IRQ_TYPE NONE
#define DIPSW_PIO_NIOS_RESET_VALUE 0

/*
 * Macros for device 'led_pio_nios', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_NIOS_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_NIOS_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_NIOS_COMPONENT_NAME led_pio_nios
#define LED_PIO_NIOS_BASE 0x20060
#define LED_PIO_NIOS_SPAN 16
#define LED_PIO_NIOS_END 0x2006f
#define LED_PIO_NIOS_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_NIOS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_NIOS_CAPTURE 0
#define LED_PIO_NIOS_DATA_WIDTH 7
#define LED_PIO_NIOS_DO_TEST_BENCH_WIRING 0
#define LED_PIO_NIOS_DRIVEN_SIM_VALUE 0
#define LED_PIO_NIOS_EDGE_TYPE NONE
#define LED_PIO_NIOS_FREQ 50000000
#define LED_PIO_NIOS_HAS_IN 0
#define LED_PIO_NIOS_HAS_OUT 1
#define LED_PIO_NIOS_HAS_TRI 0
#define LED_PIO_NIOS_IRQ_TYPE NONE
#define LED_PIO_NIOS_RESET_VALUE 127

/*
 * Macros for device 'spi_nios', class 'altera_avalon_spi'
 * The macros are prefixed with 'SPI_NIOS_'.
 * The prefix is the slave descriptor.
 */
#define SPI_NIOS_COMPONENT_TYPE altera_avalon_spi
#define SPI_NIOS_COMPONENT_NAME spi_nios
#define SPI_NIOS_BASE 0x20080
#define SPI_NIOS_SPAN 32
#define SPI_NIOS_END 0x2009f
#define SPI_NIOS_IRQ 2
#define SPI_NIOS_CLOCKMULT 1
#define SPI_NIOS_CLOCKPHASE 0
#define SPI_NIOS_CLOCKPOLARITY 0
#define SPI_NIOS_CLOCKUNITS "Hz"
#define SPI_NIOS_DATABITS 32
#define SPI_NIOS_DATAWIDTH 32
#define SPI_NIOS_DELAYMULT "1.0E-9"
#define SPI_NIOS_DELAYUNITS "ns"
#define SPI_NIOS_EXTRADELAY 0
#define SPI_NIOS_INSERT_SYNC 0
#define SPI_NIOS_ISMASTER 0
#define SPI_NIOS_LSBFIRST 0
#define SPI_NIOS_NUMSLAVES 1
#define SPI_NIOS_PREFIX "spi_"
#define SPI_NIOS_SYNC_REG_DEPTH 2
#define SPI_NIOS_TARGETCLOCK 1000000
#define SPI_NIOS_TARGETSSDELAY "0.0"

/*
 * Macros for device 'address_span_extender_0_windowed_slave', class 'altera_address_span_extender'
 * The macros are prefixed with 'ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_'.
 * The prefix is the slave descriptor.
 */
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_COMPONENT_TYPE altera_address_span_extender
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_COMPONENT_NAME address_span_extender_0
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_BASE 0x8000000
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_SPAN 134217728
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_END 0xfffffff
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_BURSTCOUNT_WIDTH 1
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_BYTEENABLE_WIDTH 4
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_CNTL_ADDRESS_WIDTH 1
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_DATA_WIDTH 32
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_MASTER_ADDRESS_WIDTH 32
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_MAX_BURST_BYTES 4
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_MAX_BURST_WORDS 1
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_SLAVE_ADDRESS_SHIFT 2
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_SLAVE_ADDRESS_WIDTH 25
#define ADDRESS_SPAN_EXTENDER_0_WINDOWED_SLAVE_SUB_WINDOW_COUNT 1


#endif /* _ALTERA_NIOS2_GEN2_0_H_ */
